/**
 * Python runner executed inside the sandbox by `execute_python`.
 *
 * The host rewrites this file before every execution, so a previous run cannot
 * leave a tampered runner behind. Protocol, one JSON object per line on the
 * real stdout, each prefixed with `PROTOCOL_PREFIX`:
 *
 * - `{"type":"rpc","id","method","params"}` — the host answers by writing
 *   `<rpc dir>/<id>.json` (`{"result": ...}` or `{"error": {...}}`).
 * - `{"type":"done", ...}` — the final structured result.
 *
 * Anything the user code prints is captured in a buffer, never mixed with the
 * protocol stream. The runner has no network access and no credentials; the
 * only way to reach Airtable is the RPC bridge.
 */

export const PROTOCOL_PREFIX = "@@codeact@@";

export const RUNNER_SOURCE = String.raw`# -*- coding: utf-8 -*-
"""execute_python runner. Generated by the host; edits are overwritten."""
import ast
import base64
import builtins
import io
import json
import os
import signal
import sys
import time
import traceback
import types
import uuid

PREFIX = "@@codeact@@"
HOME = os.environ["CODEACT_HOME"]
EXEC_ID = os.environ["CODEACT_EXEC_ID"]
TIMEOUT_S = float(os.environ.get("CODEACT_TIMEOUT_S", "60"))
MEMORY_MB = int(os.environ.get("CODEACT_MEMORY_MB", "1024"))
MAX_OUTPUT_CHARS = int(os.environ.get("CODEACT_MAX_OUTPUT_CHARS", "6000"))
MAX_CHARTS = int(os.environ.get("CODEACT_MAX_CHARTS", "4"))
MAX_TABLE_ROWS = int(os.environ.get("CODEACT_MAX_TABLE_ROWS", "50"))
STATE_PATH = os.path.join(HOME, "state", "session.pkl")
RPC_DIR = os.path.join(HOME, "rpc")
CHART_DIR = os.path.join(HOME, "charts")
CODE_PATH = os.path.join(HOME, "exec", EXEC_ID + ".py")
STARTED = time.monotonic()

# The protocol channel is a private copy of the original stdout. fd 1 is then
# pointed at stderr so stray C-level writes cannot corrupt the protocol.
_proto = os.fdopen(os.dup(1), "w", encoding="utf-8", buffering=1)
os.dup2(2, 1)


def emit(message):
    _proto.write(PREFIX + json.dumps(message, ensure_ascii=False, default=str) + "\n")
    _proto.flush()


class ExecutionTimeout(Exception):
    """Raised inside user code when the execution time limit is reached."""


def _on_alarm(signum, frame):
    raise ExecutionTimeout(
        "La ejecución superó el límite de %d segundos. Reducí los datos (filtros, menos campos) "
        "o dividí el trabajo en pasos." % TIMEOUT_S
    )


def apply_limits():
    try:
        import resource

        limit = MEMORY_MB * 1024 * 1024
        resource.setrlimit(resource.RLIMIT_AS, (limit, limit))
    except Exception:  # pragma: no cover - platform dependent
        pass
    signal.signal(signal.SIGALRM, _on_alarm)
    signal.setitimer(signal.ITIMER_REAL, TIMEOUT_S)


def remaining_s():
    return max(0.0, TIMEOUT_S - (time.monotonic() - STARTED))


# ---------------------------------------------------------------------------
# Airtable client (read-only, via the host RPC bridge)
# ---------------------------------------------------------------------------

DATA_READS = []


class AirtableError(Exception):
    """A failed Airtable read. The message explains what to change."""


def _rpc(method, params):
    request_id = uuid.uuid4().hex
    emit({"type": "rpc", "id": request_id, "method": method, "params": params})
    path = os.path.join(RPC_DIR, request_id + ".json")
    delay = 0.02
    while True:
        if os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as handle:
                    payload = json.load(handle)
            except (ValueError, OSError):
                payload = None  # the host may still be writing; retry
            if payload is not None:
                try:
                    os.remove(path)
                except OSError:
                    pass
                if "error" in payload:
                    raise AirtableError(payload["error"].get("message", "Error de Airtable"))
                return payload["result"]
        time.sleep(delay)
        delay = min(delay * 1.5, 0.25)


def _flatten_value(value):
    """Turns Airtable cell objects into plain values pandas can work with."""
    if isinstance(value, list):
        return [_flatten_value(item) for item in value]
    if isinstance(value, dict):
        if "filename" in value:
            return value.get("filename")
        if "name" in value and ("email" in value or "id" in value):
            return value.get("name")
        if "state" in value and "value" in value:  # AI text / button-like fields
            return value.get("value")
        if "label" in value:
            return value.get("label")
        return json.dumps(value, ensure_ascii=False)
    return value


class Airtable:
    """Read-only client for the authorized Airtable base.

    Discover before you query:
      airtable.list_tables()             -> DataFrame: table, table_id, fields, primary_field, description
      airtable.describe_table("Tabla")   -> DataFrame: field, type, field_id, options, description
    Read:
      airtable.records("Tabla", fields=None, formula=None, view=None, sort=None, max_records=None)
          -> DataFrame with "_id", "_created_time" and one column per field.
             Follows every page; it either returns ALL matching records or raises.
             max_records returns a declared sample: df.attrs["airtable"]["complete"] is False.
             formula uses Airtable formula syntax, e.g. "{Total} > 1000000" or
             "IS_AFTER({Issue Date}, '2026-01-01')".
             sort is a list like [{"field": "Issue Date", "direction": "desc"}].
      airtable.get_record("Tabla", "recXXXXXXXXXXXXXX") -> dict
    Every read is logged and reported back with its record count and completeness.
    Empty cells are missing in Airtable, so they become NaN/None columns here.
    """

    def __repr__(self):
        return "<Airtable read-only client; help(airtable) for usage>"

    def list_tables(self):
        import pandas as pd

        tables = _rpc("list_tables", {})
        rows = []
        for table in tables:
            primary = next(
                (f["name"] for f in table["fields"] if f["id"] == table.get("primaryFieldId")), None
            )
            rows.append(
                {
                    "table": table["name"],
                    "table_id": table["id"],
                    "fields": len(table["fields"]),
                    "primary_field": primary,
                    "description": table.get("description"),
                }
            )
        return pd.DataFrame(rows, columns=["table", "table_id", "fields", "primary_field", "description"])

    def describe_table(self, table):
        import pandas as pd

        schema = _rpc("describe_table", {"table": table})
        rows = []
        for field in schema["fields"]:
            options = field.get("options") or {}
            summary = None
            if "choices" in options:
                summary = ", ".join(choice.get("name", "") for choice in options["choices"][:30])
            elif "linkedTableId" in options:
                summary = "link -> " + str(options.get("linkedTableName") or options["linkedTableId"])
            elif "result" in options and isinstance(options["result"], dict):
                summary = "result: " + str(options["result"].get("type"))
            elif "precision" in options:
                summary = "precision: " + str(options["precision"])
            rows.append(
                {
                    "field": field["name"],
                    "type": field["type"],
                    "field_id": field["id"],
                    "options": summary,
                    "description": field.get("description"),
                }
            )
        df = pd.DataFrame(rows, columns=["field", "type", "field_id", "options", "description"])
        df.attrs["table"] = schema["name"]
        return df

    def records(self, table, fields=None, formula=None, view=None, sort=None, max_records=None):
        import pandas as pd

        if isinstance(fields, str):
            fields = [fields]
        params = {
            "table": table,
            "fields": list(fields) if fields else None,
            "formula": formula,
            "view": view,
            "sort": sort,
            "max_records": max_records,
        }
        result = _rpc("list_records", {k: v for k, v in params.items() if v is not None})
        rows = []
        for record in result["records"]:
            row = {"_id": record["id"], "_created_time": record.get("createdTime")}
            for key, value in record.get("fields", {}).items():
                row[key] = _flatten_value(value)
            rows.append(row)
        columns = ["_id", "_created_time"] + list(fields or result.get("field_order") or [])
        df = pd.DataFrame(rows)
        for column in columns:
            if column not in df.columns:
                df[column] = None
        ordered = columns + [c for c in df.columns if c not in columns]
        df = df[ordered]
        info = {
            "table": result["table"],
            "records": len(rows),
            "complete": bool(result["complete"]),
            "pages": result["pages"],
            "formula": formula,
            "view": view,
            "max_records": max_records,
        }
        df.attrs["airtable"] = info
        DATA_READS.append(info)
        if not info["complete"]:
            print(
                "AVISO: lectura parcial de '%s' (%d registros, limitada por max_records). "
                "No es el total de la tabla." % (info["table"], len(rows))
            )
        return df

    def get_record(self, table, record_id):
        record = _rpc("get_record", {"table": table, "record_id": record_id})
        fields = {key: _flatten_value(value) for key, value in record.get("fields", {}).items()}
        return {"_id": record["id"], "_created_time": record.get("createdTime"), **fields}


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------

CHARTS = []


def show_chart(fig=None, title=None):
    """Saves a matplotlib figure (the current one by default) as a chart for the user.

    Returns the chart id. Figures still open at the end of the execution are
    saved automatically, so calling this is optional; it lets you set a title.
    """
    import matplotlib.pyplot as plt

    if fig is None:
        fig = plt.gcf()
    if len(CHARTS) >= MAX_CHARTS:
        plt.close(fig)
        raise RuntimeError("Máximo %d gráficos por ejecución." % MAX_CHARTS)
    if title is None:
        title = fig._suptitle.get_text() if getattr(fig, "_suptitle", None) else None
        if not title:
            for axis in fig.axes:
                if axis.get_title():
                    title = axis.get_title()
                    break
    chart_id = "%s-%d" % (EXEC_ID, len(CHARTS) + 1)
    path = os.path.join(CHART_DIR, chart_id + ".png")
    fig.savefig(path, format="png", dpi=110, bbox_inches="tight")
    width, height = fig.get_size_inches() * 110
    plt.close(fig)
    CHARTS.append(
        {"id": chart_id, "title": title or "Gráfico", "path": path, "width": int(width), "height": int(height)}
    )
    return chart_id


def money_axis(ax=None, axis="y", prefix="$"):
    """Formats an axis as money with thousands separators: 1500000 -> $1.500.000."""
    import matplotlib.pyplot as plt
    from matplotlib.ticker import FuncFormatter

    ax = ax or plt.gca()
    formatter = FuncFormatter(lambda value, _: prefix + "{:,.0f}".format(value).replace(",", "."))
    (ax.yaxis if axis == "y" else ax.xaxis).set_major_formatter(formatter)
    return ax


def _apply_chart_style():
    import matplotlib as mpl

    mpl.rcParams.update(
        {
            "figure.figsize": (8, 4.5),
            "figure.dpi": 110,
            "axes.formatter.useoffset": False,
            "axes.formatter.limits": (-15, 15),
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": True,
            "axes.grid.axis": "y",
            "grid.alpha": 0.3,
            "axes.titleweight": "bold",
        }
    )


def _flush_open_figures():
    if "matplotlib.pyplot" not in sys.modules:
        return
    import matplotlib.pyplot as plt

    for number in list(plt.get_fignums()):
        figure = plt.figure(number)
        if not figure.axes:
            plt.close(figure)
            continue
        if len(CHARTS) >= MAX_CHARTS:
            plt.close(figure)
            continue
        show_chart(figure)


# ---------------------------------------------------------------------------
# Result rendering
# ---------------------------------------------------------------------------


def _truncate(text, limit=MAX_OUTPUT_CHARS):
    if len(text) <= limit:
        return text, False
    return text[:limit] + "\n… (salida truncada, %d caracteres más)" % (len(text) - limit), True


def _json_cell(value):
    try:
        import numpy as np
        import pandas as pd

        if value is None or (isinstance(value, float) and value != value):
            return None
        if isinstance(value, (pd.Timestamp,)):
            return value.isoformat()
        if isinstance(value, np.generic):
            return value.item()
    except Exception:
        pass
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def render_value(value):
    try:
        import pandas as pd
    except Exception:  # pragma: no cover
        pd = None
    if pd is not None and isinstance(value, pd.Series):
        value = value.to_frame()
    if pd is not None and isinstance(value, pd.DataFrame):
        frame = value
        if not isinstance(frame.index, pd.RangeIndex):
            frame = frame.reset_index()
        head = frame.head(MAX_TABLE_ROWS)
        rows = [[_json_cell(cell) for cell in row] for row in head.itertuples(index=False, name=None)]
        return {
            "kind": "table",
            "columns": [str(column) for column in head.columns],
            "rows": rows,
            "total_rows": int(len(frame)),
            "truncated": bool(len(frame) > MAX_TABLE_ROWS),
        }
    text, truncated = _truncate(repr(value), 2000)
    return {"kind": "text", "text": text, "truncated": truncated}


# ---------------------------------------------------------------------------
# State persistence
# ---------------------------------------------------------------------------

RESERVED = {"airtable", "AirtableError", "show_chart", "money_axis", "pd", "np", "plt", "ExecutionTimeout"}


def _serializer():
    try:
        import dill

        return dill
    except Exception:
        import pickle

        return pickle


def load_state(namespace):
    warnings = []
    if not os.path.exists(STATE_PATH):
        return warnings
    try:
        with open(STATE_PATH, "rb") as handle:
            stored = _serializer().load(handle)
    except Exception as error:
        warnings.append("No pude restaurar las variables anteriores (%s); empiezo de cero." % error)
        return warnings
    import importlib

    for name, module_name in stored.get("modules", {}).items():
        try:
            namespace[name] = importlib.import_module(module_name)
        except Exception:
            pass
    for name, blob in stored.get("values", {}).items():
        try:
            namespace[name] = _serializer().loads(blob)
        except Exception:
            warnings.append("No pude restaurar la variable '%s'." % name)
    return warnings


def save_state(namespace):
    serializer = _serializer()
    values, modules, skipped = {}, {}, []
    for name, value in list(namespace.items()):
        if name.startswith("_") or name in RESERVED:
            continue
        if isinstance(value, types.ModuleType):
            modules[name] = value.__name__
            continue
        try:
            blob = serializer.dumps(value)
        except Exception:
            skipped.append(name)
            continue
        if len(blob) > 200 * 1024 * 1024:
            skipped.append(name)
            continue
        values[name] = blob
    tmp_path = STATE_PATH + ".tmp"
    with open(tmp_path, "wb") as handle:
        serializer.dump({"values": values, "modules": modules}, handle)
    os.replace(tmp_path, STATE_PATH)
    return skipped


def describe_variables(namespace):
    import pandas as pd

    described = []
    for name, value in namespace.items():
        if name.startswith("_") or name in RESERVED or isinstance(value, types.ModuleType):
            continue
        if callable(value) and not isinstance(value, (pd.DataFrame, pd.Series)):
            described.append({"name": name, "type": type(value).__name__})
            continue
        entry = {"name": name, "type": type(value).__name__}
        if isinstance(value, pd.DataFrame):
            entry["shape"] = [int(value.shape[0]), int(value.shape[1])]
            entry["columns"] = [str(column) for column in value.columns[:25]]
            if "airtable" in value.attrs:
                entry["source"] = value.attrs["airtable"]
        elif isinstance(value, pd.Series):
            entry["shape"] = [int(value.shape[0])]
        elif isinstance(value, (int, float, str, bool)):
            entry["value"] = _truncate(repr(value), 200)[0]
        elif isinstance(value, (list, dict, tuple, set)):
            entry["length"] = len(value)
        described.append(entry)
    return described[:40]


# ---------------------------------------------------------------------------
# Execution
# ---------------------------------------------------------------------------


def format_error(error, source_lines):
    frames = [
        frame
        for frame in traceback.extract_tb(error.__traceback__)
        if frame.filename == "<execute_python>"
    ]
    line = frames[-1].lineno if frames else getattr(error, "lineno", None)
    snippet = None
    if line is not None and 0 < line <= len(source_lines):
        snippet = source_lines[line - 1].strip()
    lines = traceback.format_exception(type(error), error, error.__traceback__)
    # Drop runner frames; keep the user's code frames and library frames below them.
    filtered, keep = [], False
    for entry in lines:
        if entry.startswith("Traceback"):
            filtered.append(entry)
            continue
        if '"<execute_python>"' in entry:
            keep = True
        if keep or not entry.startswith("  File"):
            filtered.append(entry)
    text, _ = _truncate("".join(filtered), 3000)
    return {
        "type": type(error).__name__,
        "message": str(error)[:1000],
        "line": line,
        "code_line": snippet,
        "traceback": text,
    }


def main():
    os.environ.setdefault("MPLBACKEND", "Agg")
    os.makedirs(RPC_DIR, exist_ok=True)
    os.makedirs(CHART_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(STATE_PATH), exist_ok=True)
    os.makedirs(os.path.join(HOME, "mplconfig"), exist_ok=True)
    os.environ.setdefault("MPLCONFIGDIR", os.path.join(HOME, "mplconfig"))

    with open(CODE_PATH, "r", encoding="utf-8") as handle:
        source = handle.read()

    captured = io.StringIO()
    sys.stdout = captured
    sys.stderr = captured

    apply_limits()

    namespace = {"__name__": "__main__", "__builtins__": builtins}
    warnings = []
    error = None
    result = None
    skipped = []
    try:
        import numpy as np
        import pandas as pd
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        _apply_chart_style()

        pd.set_option("display.width", 160)
        pd.set_option("display.max_columns", 30)
        namespace.update(
            {
                "pd": pd,
                "np": np,
                "plt": plt,
                "airtable": Airtable(),
                "AirtableError": AirtableError,
                "show_chart": show_chart,
                "money_axis": money_axis,
            }
        )
        warnings.extend(load_state(namespace))

        tree = ast.parse(source, filename="<execute_python>", mode="exec")
        last_expr = None
        if tree.body and isinstance(tree.body[-1], ast.Expr):
            last_expr = ast.Expression(tree.body.pop().value)
        exec(compile(tree, "<execute_python>", "exec"), namespace)
        if last_expr is not None:
            value = eval(compile(last_expr, "<execute_python>", "eval"), namespace)
            if value is not None:
                result = render_value(value)
        _flush_open_figures()
    except BaseException as caught:  # noqa: BLE001 - report everything to the model
        if isinstance(caught, SystemExit) and not caught.code:
            pass
        else:
            error = format_error(caught, source.splitlines())
        try:
            _flush_open_figures()
        except BaseException:
            pass
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)

    try:
        skipped = save_state(namespace)
    except BaseException as caught:  # noqa: BLE001
        warnings.append("No pude guardar las variables para la próxima ejecución (%s)." % caught)

    try:
        variables = describe_variables(namespace)
    except BaseException:
        variables = []

    stdout_text, stdout_truncated = _truncate(captured.getvalue())
    emit(
        {
            "type": "done",
            "ok": error is None,
            "stdout": stdout_text,
            "stdout_truncated": stdout_truncated,
            "result": result,
            "error": error,
            "charts": CHARTS,
            "data_reads": DATA_READS,
            "variables": variables,
            "not_persisted": skipped,
            "warnings": warnings,
            "duration_ms": int((time.monotonic() - STARTED) * 1000),
        }
    )


if __name__ == "__main__":
    main()
`;
